version: "3.8"

services:
  mysqldb:
    image: mariadb:10.5.22
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_TCP_PORT=$MYSQLDB_LOCAL_PORT
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - type: tmpfs
        target: /var/lib/mysql
    healthcheck:
      test: "healthcheck.sh --connect"
      interval: 2s
      timeout: 5s
      retries: 20
      start_period: 2s
  app:
    depends_on:
      mysqldb:
        condition: service_healthy
    build: ./
    restart: on-failure
    env_file: .env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.sql.init.mode" : "always",
        "spring.datasource.initialization-mode" : "always" }'
    volumes:
      - /Users/rodmidde/.m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:
